-- 2026-07-07: Satın Alma-Lite modülü — kritik stok → tedarikçi bazlı sipariş
-- önerisi → sipariş kaydı → mal kabul → ledger'a stok girişi (apply_stock_move
-- üzerinden). Canlıya tek sefer: python tools/run_sql.py supabase/migrate_20260707_purchasing.sql
-- current_role_of() ve apply_stock_move() schema.sql'de tanımlı (önce o kurulur).

-- ─── Siparişler ─────────────────────────────────────────────────────────────
create table if not exists purchase_orders (
    id         bigint generated by default as identity primary key,
    supplier   text not null,
    status     text not null default 'taslak'
               check (status in ('taslak', 'siparis', 'kismi', 'kapandi', 'iptal')),
    note       text not null default '',
    created_by uuid default auth.uid(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists purchase_orders_status_idx on purchase_orders (status);

-- ─── Sipariş satırları ──────────────────────────────────────────────────────
create table if not exists purchase_order_lines (
    id           bigint generated by default as identity primary key,
    po_id        bigint not null references purchase_orders(id) on delete cascade,
    item_id      bigint not null references items(id),
    qty          integer not null check (qty > 0),
    received_qty integer not null default 0 check (received_qty >= 0)
);
create index if not exists purchase_order_lines_po_idx on purchase_order_lines (po_id);
create index if not exists purchase_order_lines_item_idx on purchase_order_lines (item_id);

-- updated_at otomatik (crm_touch_updated deseniyle aynı; ayrı fonksiyon —
-- satın alma modülü CRM şemasına bağımlı olmasın diye kendi tetikleyicisi var)
create or replace function po_touch_updated() returns trigger
language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists purchase_orders_touch on purchase_orders;
create trigger purchase_orders_touch before update on purchase_orders
    for each row execute function po_touch_updated();

-- ─── RLS: girişli herkes okur; yönetici+üretim yazar (CRM verisi karışmaz) ──
alter table purchase_orders      enable row level security;
alter table purchase_order_lines enable row level security;

drop policy if exists purchase_orders_read on purchase_orders;
drop policy if exists purchase_orders_write on purchase_orders;
create policy purchase_orders_read on purchase_orders for select using (auth.uid() is not null);
create policy purchase_orders_write on purchase_orders for all
    using (current_role_of() in ('yonetici', 'uretim'))
    with check (current_role_of() in ('yonetici', 'uretim'));

drop policy if exists purchase_order_lines_read on purchase_order_lines;
drop policy if exists purchase_order_lines_write on purchase_order_lines;
create policy purchase_order_lines_read on purchase_order_lines for select using (auth.uid() is not null);
create policy purchase_order_lines_write on purchase_order_lines for all
    using (current_role_of() in ('yonetici', 'uretim'))
    with check (current_role_of() in ('yonetici', 'uretim'));

-- ─── Mal kabul: satır received_qty'yi artırır + items/ledger'a atomik giriş
-- yapar (apply_stock_move) + PO durumunu otomatik günceller. security definer
-- olsa da rol denetimi içeride tekrarlanır (RLS zaten write'ı kısıtlar; bu
-- ikinci savunma katmanı — apply_stock_move de security definer'dır).
create or replace function receive_po_line(line_id bigint, recv_qty integer)
returns purchase_order_lines language plpgsql security definer set search_path = public as $$
declare
    v_line       purchase_order_lines;
    v_po         purchase_orders;
    v_user_name  text;
    v_total_qty  integer;
    v_total_recv integer;
    v_new_status text;
begin
    if current_role_of() not in ('yonetici', 'uretim') then
        raise exception 'yetkisiz: mal kabul yalnız yönetici/üretim yapabilir';
    end if;
    if recv_qty is null or recv_qty <= 0 then
        raise exception 'miktar 0''dan büyük olmalı';
    end if;

    update purchase_order_lines
       set received_qty = received_qty + recv_qty
     where id = line_id
     returning * into v_line;
    if not found then raise exception 'sipariş satırı % yok', line_id; end if;

    select * into v_po from purchase_orders where id = v_line.po_id for update;
    if v_po.status in ('iptal', 'kapandi') then
        raise exception 'sipariş % durumunda mal kabul yapılamaz', v_po.status;
    end if;

    select full_name into v_user_name from profiles where user_id = auth.uid();
    -- DİKKAT: ref öneki 'PO-' DEĞİL — production_orders'ın complete_production_order
    -- RPC'si zaten stock_moves.ref = 'PO-' || production_order_id kullanıyor (Production
    -- Order). Aynı öneki satın alma siparişi için de kullanmak aynı sayısal id'de
    -- (ör. üretim emri #1 ile satın alma siparişi #1) ref çakışmasına yol açar —
    -- defter/audit sorgularında iki farklı kaynağı ayırt edilemez kılar.
    perform apply_stock_move(v_line.item_id, 'in', recv_qty,
        'Mal kabul — PO#' || v_po.id, 'SATINALMA-' || v_po.id, coalesce(v_user_name, ''));

    select coalesce(sum(qty), 0), coalesce(sum(received_qty), 0)
      into v_total_qty, v_total_recv
      from purchase_order_lines where po_id = v_po.id;

    v_new_status := case
        when v_total_recv >= v_total_qty then 'kapandi'
        when v_total_recv > 0 then 'kismi'
        else v_po.status
    end;
    if v_new_status is distinct from v_po.status then
        update purchase_orders set status = v_new_status where id = v_po.id;
    end if;

    return v_line;
end $$;
