-- 2026-07-06: Basit seri no takibi — üretilen her cihaza seri, üretim emrine bağlı.
-- Canlıya: python tools/run_sql.py supabase/migrate_20260706_serials.sql

create table if not exists unit_serials (
    id           bigint generated by default as identity primary key,
    serial       text not null unique,
    item_id      bigint references items(id),
    product_name text not null default '',
    order_id     bigint references production_orders(id) on delete set null,
    status       text not null default 'produced'
                 check (status in ('produced', 'tested', 'shipped')),
    note         text not null default '',
    created_at   timestamptz not null default now()
);
create index if not exists unit_serials_item_idx on unit_serials (item_id, created_at desc);

alter table unit_serials enable row level security;
drop policy if exists unit_serials_read on unit_serials;
drop policy if exists unit_serials_write on unit_serials;
create policy unit_serials_read on unit_serials for select using (auth.uid() is not null);
create policy unit_serials_write on unit_serials for all
    using (current_role_of() in ('yonetici', 'uretim'))
    with check (current_role_of() in ('yonetici', 'uretim'));
