-- 2026-07-07: Cari Kartotek — partners (müşteri + tedarikçi kartları).
-- Satın alma siparişi tedarikçi kartına, CRM fırsatı müşteri kartının şirketine
-- bağlanır (partner_id köprüsü). Canlıya tek sefer:
--   python tools/run_sql.py supabase/migrate_20260707_partners.sql
-- current_role_of() schema.sql'de, crm_deals crm_schema.sql'de,
-- purchase_orders migrate_20260707_purchasing.sql'de önce kurulmuş olmalı.

-- ─── Kartlar ────────────────────────────────────────────────────────────────
create table if not exists partners (
    id              bigint generated by default as identity primary key,
    name            text not null,
    kind            text not null check (kind in ('musteri', 'tedarikci')),
    contact_person  text not null default '',
    email           text not null default '',
    phone           text not null default '',
    address         text not null default '',
    country         text not null default '',
    note            text not null default '',
    archived        boolean not null default false,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);
-- Aynı türde aynı ad iki kez kaydedilemez (case-insensitive) — tedarikçi ve
-- müşteri isim uzayı ayrı tutulur (ör. hem "Aqua Pools" tedarikçi hem müşteri
-- olabilir, çakışma sayılmaz).
create unique index if not exists partners_kind_name_uidx on partners (kind, lower(name));

create or replace function partners_touch_updated() returns trigger
language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists partners_touch on partners;
create trigger partners_touch before update on partners
    for each row execute function partners_touch_updated();

-- ─── RLS ────────────────────────────────────────────────────────────────────
-- Tedarikçi kartları operasyonel = girişli herkes okur (üretim dahil).
-- Müşteri kartları CRM verisi = yalnız yönetici + satış okur (CRM RLS emsali,
-- üretim rolü tek satır bile göremez).
alter table partners enable row level security;

drop policy if exists partners_read on partners;
create policy partners_read on partners for select using (
    (kind = 'tedarikci' and auth.uid() is not null)
    or (kind = 'musteri' and current_role_of() in ('yonetici', 'satis'))
);

-- Yazma: yönetici her iki türü de yazar; üretim yalnız tedarikçi; satış yalnız
-- müşteri (with check + using ikisinde de kind koşullu — hem var olan satırın
-- hem yeni/değişecek satırın türü kontrol edilir).
drop policy if exists partners_write on partners;
create policy partners_write on partners for all
    using (
        current_role_of() = 'yonetici'
        or (current_role_of() = 'uretim' and kind = 'tedarikci')
        or (current_role_of() = 'satis' and kind = 'musteri')
    )
    with check (
        current_role_of() = 'yonetici'
        or (current_role_of() = 'uretim' and kind = 'tedarikci')
        or (current_role_of() = 'satis' and kind = 'musteri')
    );

-- ─── Köprü kolonları ────────────────────────────────────────────────────────
alter table purchase_orders add column if not exists partner_id bigint references partners(id);
alter table crm_deals       add column if not exists partner_id bigint references partners(id);
create index if not exists purchase_orders_partner_idx on purchase_orders (partner_id);
create index if not exists crm_deals_partner_idx on crm_deals (partner_id);

-- ─── Seed (idempotent) ──────────────────────────────────────────────────────
-- Tedarikçi kartları: items.supplier'daki distinct dolu değerler (Mean Well,
-- Delta, Mervesan, 3M, Danfoss, Loctite, Telemecanique, Ömer Kablo — dış üretim
-- fasoncusu, zaten items.supplier'da bir satırda kayıtlı).
insert into partners (name, kind)
select distinct trim(supplier), 'tedarikci'
from items
where supplier is not null and trim(supplier) <> ''
on conflict (kind, lower(name)) do nothing;

-- Müşteri kartları: crm_deals'daki distinct şirket adları.
insert into partners (name, kind)
select distinct trim(company), 'musteri'
from crm_deals
where company is not null and trim(company) <> ''
on conflict (kind, lower(name)) do nothing;

-- Backfill: crm_deals.partner_id / purchase_orders.partner_id — birebir ad
-- eşleşmesi (case-insensitive). IS DISTINCT FROM guard = gereksiz satırlarda
-- touch tetikleyicisini (updated_at) tetiklemesin.
update crm_deals d
   set partner_id = p.id
  from partners p
 where p.kind = 'musteri'
   and lower(p.name) = lower(trim(d.company))
   and d.partner_id is distinct from p.id;

update purchase_orders po
   set partner_id = p.id
  from partners p
 where p.kind = 'tedarikci'
   and lower(p.name) = lower(trim(po.supplier))
   and po.partner_id is distinct from p.id;
