-- Aquatronic ERP — Faz 1 çekirdek şema (Supabase Postgres)
-- Kurulum: Supabase Dashboard → SQL Editor → bu dosyayı yapıştır → Run.
-- Tasarım ilkeleri:
--   * stock_moves = hakikat defteri (ledger); items.qty önbellek kolonudur ve
--     stok hareketi RPC'leri içinde atomik güncellenir.
--   * Silme yok: items.archived. Roller: yonetici / uretim / satis (profiles).
--   * CRM tabloları BU FAZDA YOK (Sheets köprüsü sürüyor; CRM fazında taşınacak).

-- ─── Roller / profiller ────────────────────────────────────────────────────
create table if not exists profiles (
    user_id    uuid primary key references auth.users(id) on delete cascade,
    full_name  text not null,
    role       text not null check (role in ('yonetici', 'uretim', 'satis')),
    created_at timestamptz not null default now()
);

-- Yardımcı: istekteki kullanıcının rolü
create or replace function current_role_of()
returns text language sql stable security definer set search_path = public as
$$ select role from profiles where user_id = auth.uid() $$;

-- ─── Ürünler ───────────────────────────────────────────────────────────────
create table if not exists items (
    id        bigint generated by default as identity primary key,
    name      text not null unique,
    family    text not null,
    cat       text not null default '',
    qty       integer not null default 0 check (qty >= 0),
    critical  integer not null default 0,
    note      text not null default '',
    photo     text,                       -- storage yolu ya da foto/<dosya>
    box_qty   integer,
    weight    numeric,
    tr        text not null default '',  -- Türkçe arama etiketi
    archived  boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists items_family_idx on items (family) where not archived;

-- ─── Stok hareket defteri (LEDGER — hakikat kaynağı) ───────────────────────
create table if not exists stock_moves (
    id         bigint generated by default as identity primary key,
    item_id    bigint not null references items(id),
    move_type  text not null check (move_type in ('in', 'out', 'count', 'consume', 'produce')),
    qty        integer not null,          -- imzalı: in/produce +, out/consume -; count = yeni-eski farkı
    qty_after  integer not null,          -- hareket sonrası items.qty (denetim kolaylığı)
    note       text not null default '',
    ref        text not null default '',  -- ör. üretim emri no
    user_name  text not null default '',
    created_at timestamptz not null default now()
);
create index if not exists stock_moves_item_idx on stock_moves (item_id, created_at desc);

-- Atomik stok hareketi: qty günceller + ledger yazar (app her zaman bunu çağırır)
create or replace function apply_stock_move(
    p_item_id bigint, p_move_type text, p_qty integer,
    p_note text default '', p_ref text default '', p_user text default ''
) returns items language plpgsql security definer set search_path = public as $$
declare v_item items;
begin
    update items
       set qty = greatest(0, qty + p_qty), updated_at = now()
     where id = p_item_id
     returning * into v_item;
    if not found then raise exception 'item % yok', p_item_id; end if;
    insert into stock_moves (item_id, move_type, qty, qty_after, note, ref, user_name)
    values (p_item_id, p_move_type, p_qty, v_item.qty, p_note, p_ref, p_user);
    return v_item;
end $$;

-- ─── BOM (ürün reçetesi) ───────────────────────────────────────────────────
create table if not exists boms (
    product_id   bigint not null references items(id) on delete cascade,
    component_id bigint not null references items(id),
    qty          integer not null check (qty > 0),
    primary key (product_id, component_id),
    check (product_id <> component_id)
);

-- ─── Üretim emirleri (planned → active → done) ─────────────────────────────
create table if not exists production_orders (
    id           bigint generated by default as identity primary key,
    item_id      bigint references items(id),
    product_name text not null,            -- katalog dışı işler için serbest ad
    qty          integer not null check (qty > 0),
    status       text not null default 'planned' check (status in ('planned', 'active', 'done')),
    cat          text not null default '', -- planlı kartlardaki kategori etiketi
    note         text not null default '',
    pdf_path     text not null default '', -- storage 'erp-files' içindeki plan PDF yolu
    source_deal_id text not null default '', -- Faz 2 köprüsü: bağlı CRM fırsatı (opak ID)
    user_name    text not null default '',
    created_at   timestamptz not null default now(),
    started_at   timestamptz,
    completed_at timestamptz
);

-- Emri tamamla: bitmiş ürünü stoğa ekler + BOM komponentlerini tüketir (tek işlem)
create or replace function complete_production_order(p_order_id bigint, p_user text default '')
returns production_orders language plpgsql security definer set search_path = public as $$
declare v_ord production_orders; v_bom record;
begin
    update production_orders
       set status = 'done', completed_at = now()
     where id = p_order_id and status = 'active'
     returning * into v_ord;
    if not found then raise exception 'aktif emir % yok', p_order_id; end if;

    if v_ord.item_id is not null then
        perform apply_stock_move(v_ord.item_id, 'produce', v_ord.qty,
            'Üretim tamamlandı', 'PO-' || v_ord.id, p_user);
        for v_bom in select component_id, qty from boms where product_id = v_ord.item_id loop
            perform apply_stock_move(v_bom.component_id, 'consume', -(v_bom.qty * v_ord.qty),
                'Üretim tüketimi — ' || v_ord.product_name || ' ×' || v_ord.qty,
                'PO-' || v_ord.id, p_user);
        end loop;
    end if;
    return v_ord;
end $$;

-- Faz 2 köprüsü: CRM fırsatından PLANLI üretim emri açar. security definer —
-- CRM yetkilisi (yönetici/satış) üretim-yazma iznine sahip olmasa da açabilir.
create or replace function create_order_from_deal(
    p_deal_id text, p_item_id bigint, p_product_name text,
    p_qty integer, p_note text default '', p_user text default ''
) returns production_orders language plpgsql security definer set search_path = public as $$
declare v_ord production_orders;
begin
    if current_role_of() not in ('yonetici', 'satis') then
        raise exception 'yetkisiz: fırsattan emri yalnız yönetici/satış açar';
    end if;
    if p_qty is null or p_qty <= 0 then raise exception 'adet 0''dan büyük olmalı'; end if;
    insert into production_orders
        (item_id, product_name, qty, status, cat, note, source_deal_id, user_name)
    values (p_item_id, p_product_name, p_qty, 'planned', 'CRM', p_note, p_deal_id, p_user)
    returning * into v_ord;
    return v_ord;
end $$;
create index if not exists production_orders_deal_idx
    on production_orders (source_deal_id) where source_deal_id <> '';

-- ─── Havuz testi istasyonu ─────────────────────────────────────────────────
create table if not exists pool_tests (
    id           bigint generated by default as identity primary key,
    device       text not null,
    sn           text not null default '',
    "desc"       text not null default '',
    status       text not null default '',
    address      text not null default '',   -- DMX adresi
    current_idle text not null default '',
    current_run  text not null default '',
    height       text not null default '',
    start_date   text not null default '',
    end_date     text not null default '',
    notes        text not null default '',
    created_at   timestamptz not null default now()
);

-- ─── Dış üretim (fason — Ömer Kablo vb.) ───────────────────────────────────
-- Alanlar netlify/npoint Ömer Kablo yapısının birebiri
create table if not exists outsource_jobs (
    id            bigint generated by default as identity primary key,
    partner       text not null default 'Ömer Kablo',
    item          text not null default '',
    qty           text not null default '',
    status        text not null default '',
    req_date      text not null default '',
    given_mat     text not null default '',
    received_qty  text not null default '',
    received_date text not null default '',
    price         text not null default '',
    note          text not null default '',
    created_at    timestamptz not null default now()
);

-- ─── Uygulama olay günlüğü ─────────────────────────────────────────────────
create table if not exists activity_log (
    id         bigint generated by default as identity primary key,
    user_name  text not null default '',
    action     text not null,
    target     text not null default '',
    details    text not null default '',
    created_at timestamptz not null default now()
);
create index if not exists activity_log_time_idx on activity_log (created_at desc);

-- Yeni auth kullanıcısına otomatik profil (Dashboard'dan eklenenler dahil).
-- Ad/rol user_metadata'dan; yoksa ad=e-posta yereli, rol=uretim (en dar yetki).
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
    insert into profiles (user_id, full_name, role)
    values (new.id,
            coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
            coalesce(new.raw_user_meta_data->>'role', 'uretim'))
    on conflict (user_id) do nothing;
    return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
    for each row execute function handle_new_user();

-- ─── RLS: yalnız girişli kullanıcı; yazma rolleri ──────────────────────────
alter table profiles          enable row level security;
alter table items             enable row level security;
alter table stock_moves       enable row level security;
alter table boms              enable row level security;
alter table production_orders enable row level security;
alter table pool_tests        enable row level security;
alter table outsource_jobs    enable row level security;
alter table activity_log      enable row level security;

-- ─── Storage: erp-files kovası (plan PDF'leri + ürün fotoğrafları) ─────────
-- Public okuma (URL ile servis edilir), yazma yalnız girişli kullanıcı.
insert into storage.buckets (id, name, public)
values ('erp-files', 'erp-files', true)
on conflict (id) do update set public = true;
drop policy if exists erp_files_select on storage.objects;
drop policy if exists erp_files_insert on storage.objects;
drop policy if exists erp_files_update on storage.objects;
drop policy if exists erp_files_delete on storage.objects;
-- SELECT şart: storage API yükleme öncesi varlık kontrolü/upsert için okur
create policy erp_files_select on storage.objects for select to authenticated
    using (bucket_id = 'erp-files');
create policy erp_files_insert on storage.objects for insert to authenticated
    with check (bucket_id = 'erp-files');
create policy erp_files_update on storage.objects for update to authenticated
    using (bucket_id = 'erp-files') with check (bucket_id = 'erp-files');
create policy erp_files_delete on storage.objects for delete to authenticated
    using (bucket_id = 'erp-files');

-- Herkes (girişli) kendi profilini okur; yönetici hepsini yönetir
create policy profiles_self_read on profiles for select
    using (user_id = auth.uid() or current_role_of() = 'yonetici');
create policy profiles_admin_write on profiles for all
    using (current_role_of() = 'yonetici') with check (current_role_of() = 'yonetici');

-- Operasyon tabloları: girişli herkes okur; yönetici+üretim yazar
do $$ declare t text;
begin
    foreach t in array array['items','stock_moves','boms','production_orders','pool_tests','outsource_jobs','activity_log'] loop
        execute format('create policy %I_read on %I for select using (auth.uid() is not null)', t, t);
        execute format(
            'create policy %I_write on %I for all using (current_role_of() in (''yonetici'',''uretim'')) with check (current_role_of() in (''yonetici'',''uretim''))',
            t, t);
    end loop;
end $$;
